#!/usr/bin/env python3
"""Internal planning examples only; no assets, narration or film rendering."""
import copy,json,sys
from pathlib import Path
sys.dont_write_bytecode=True
from motif_quality import ROOT,write,plan_check
from build_quality_fixtures import contract
P=ROOT/'quality/validation/structure-v1'

def beat(id_,speech,hero,action,before,after,composition,role='participant'):
 q=contract();q.update(hero=hero,primary_action=action,before=before,after=after,purpose=speech,environment=['paper backboard','work surface'],secondary_motion=[],focal_target=hero,exit_overlap=None)
 q['energy']={'dominant_action':action}
 q['art_direction'].update(materials=['printed paper','card supports'],depth_planes=['paper backboard','hero and contact plane'],hero_object=hero,bot_role=role,composition=composition,intentional_irregularity='A corner crop directs attention to the active contact.',environment_mode='physical',environment_justification=None)
 q['performance']={'state':'absent' if role=='absent' else 'focused','target':'' if role=='absent' else 'bot'}
 return {'id':id_,'narration':speech,'quality':q}

def fixture(name,specs,rules,expected,token=None):
 folder=P/'fixtures-clean'/name
 if folder.exists():raise ValueError('preserve previous fixture: '+name)
 beats=[beat('b'+str(i+1),*s) for i,s in enumerate(specs)]
 script=' '.join(b['narration'] for b in beats);words=script.split();start=0;setups=[]
 for i,r in enumerate(rules):
  ids=r['beats'];selected=[b for b in beats if b['id'] in ids];text=' '.join(b['narration'] for b in selected);end=start+len(text.split());art=selected[0]['quality']['art_direction']
  setups.append({'setup_id':'s'+str(i+1),'chapter':'argument','narration_span':{'start_word':start,'end_word':end,'text':text},'semantic_center':r['center'],'visual_rule':r['rule'],'relationship_archetype':r.get('archetype','physical interaction'),'hero':selected[0]['quality']['hero'],'bot_role':art['bot_role'],'continuity_tokens':[token['id']] if token else [],'environment_mode':'physical','palette_family':r.get('palette','warm paper / teal'),'entry_state':selected[0]['quality']['before'],'exit_state':selected[-1]['quality']['after'],'reason_for_persistence':r['persistence'],'planned_reset_after':{'kind':'end' if i==len(rules)-1 else 'hard-cut','reason':r.get('reset','The argument ends in this visible consequence.')},'beat_ids':ids});start=end
 plan={'quality_mode':'motif-gold-v1','script':script,'asset_usage':[{'id':'planning-paper','scope':'production-specific','path':'','metadata_path':'','agent_assisted':True}],'beats':beats,'film_structure':{'version':'structure-1.0','rhetorical_chapters':[{'id':'argument','purpose':'Develop the supplied short argument through visible changes.','narration_span':{'start_word':0,'end_word':len(words),'text':script}}],'setups':setups,'continuity_tokens':[token] if token else []}}
 write(folder/'production-plan.json',plan);write(folder/'expected.json',{'expected':expected,'scope':'Withheld from independent critic. Planning evidence only; no execution/art approval.'});plan_check(plan)

def main():
 composition='One central physical slab occupies the middle; Bot is small at left; fixed wide camera and paper wall/floor.'
 # A: six different operating principles, all retained in one miniature world.
 specs=[]
 for speech,hero,action in [('Save the prior state.','archive','Bot copies a snapshot into the archive.'),('Show the changed lines.','diff lens','Bot opens a split lens to reveal edited lines.'),('Test the new behavior.','water tank','Bot fills a tank over the live house to test leaks.'),('Authorize the next write.','permission gate','Bot presses a separate gate and releases a write lever.'),('Route the new output.','pipeline','Bot sends the house result through a branching pipe.'),('Reverse the failed operation.','rewind crank','Bot cranks another mechanism to retrieve an old roof.')]:
  specs.append((speech,hero,action,'House plus all previously introduced operating machines remain visible.','New machine added; all previous machines remain fully opaque and active.',composition))
 fixture('a',specs,[{'beats':['b'+str(i) for i in range(1,7)],'center':'All aspects of automation','rule':'A house contains a different machine for each new software operation.','persistence':'Keep the house and every machine to brand the entire argument.'}],['METAPHOR_OVERLOAD'])
 fixture('b',[(s,h,a,'Unchanged central slab.','The local hero changes state.',composition) for s,h,a in [('Choose the closest answer.','target','Bot moves a dart onto the closest circle.'),('The cost keeps growing.','receipt tray','Bot stacks receipts on a tray.'),('Unlock the next step.','permission switch','Bot depresses a latch to release a route.')]], [{'beats':['b'+str(i+1)],'center':c,'rule':r,'persistence':'This single action serves this proposition.','reset':'The semantic relationship changes, so cut to a new hero.'} for i,(c,r) in enumerate([('accuracy','Distance to the target encodes accuracy.'),('cost','Adding receipts increases burden.'),('permission','Only a depressed latch opens a route.')])],['COMPOSITIONAL_STAGNATION'])
 fixture('c',[('This answer is selected.','candidate sheet','Bot selects a candidate while a equally large independent cost stack collapses at right and a bug scanner simultaneously reports findings at left.','Candidate, cost pile and scanner are equally large and visually active.','Three unrelated large result regions change together.','Three equal thirds: selection, cost collapse, bug discovery. All insist on equal attention.')],[{'beats':['b1'],'center':'Select a candidate','rule':'The chosen candidate rises above alternatives.','persistence':'Show selection along with unrelated demonstrations to keep the frame energetic.'}],['SEMANTIC_GROUP_OVERLOAD','COMPETING_FOCI'])
 fixture('d',[('Every request adds a cost.','receipt scale','Bot feeds twenty receipts into one tray in staggered groups.','The tray is empty and level.','Twenty paper receipts lower the SAME tray; all movement points to the load increasing.','One broad scale tray is the focal region; receipts form one cost group. A nearby spring recoils locally.')],[{'beats':['b1'],'center':'Rising cost','rule':'Receipt mass lowers the tray.','archetype':'burden / accumulation','persistence':'Each added receipt develops the same visible load.'}],['PASS'])
 fixture('e',[(speech,'inspected document',action,before,after,'A single large page and traveling lens occupy the center; Bot operates at its right edge.') for speech,action,before,after in [('Inspect the entire page.','Bot feeds a page under the lens.','Page waits at the slot.','Page reaches the lens.'),('Reveal the hidden marks.','The lens exposes previously covered marks on the same page.','Marks are concealed.','Marks are visible under the lens.'),('Repair what was found.','Bot aligns replacement patches over those marks.','Revealed marks interrupt the printed routes.','Patched routes reconnect.'),('Release the checked page.','Bot advances the SAME page out of the lens.','The patched page is under inspection.','The connected page exits intact.')]], [{'beats':['b1','b2','b3','b4'],'center':'Resolve the findings on one page','rule':'Inspection reveals broken routes on the same page, which are patched before release.','archetype':'inspection','persistence':'The longer setup evolves a single page through inspection, repair and release; no unrelated mechanism is introduced.'}],['PASS'])
 fixture('f', [('Inspect the document first.','document lens','Bot exposes a broken line.','A document enters the inspection stage.','The lens exposes a broken line.','The inspection lens and page occupy one center.'),('Then measure its price.','cost tray','Bot piles receipts on a tray while old inspection lens, scanner cables and stamping machinery stay large, opaque and animated beside it.','The story no longer discusses inspection, but its machinery remains active.','The cost tray moves while discarded inspection machinery continues taking equal space.','Cost tray shares the frame with obsolete lens, cables and stamps that have no current story or location purpose.')], [{'beats':['b1'],'center':'Find a break','rule':'The lens exposes a route gap.','persistence':'Inspect this page.','reset':'New semantic rule: cost should be a new setup.'},{'beats':['b2'],'center':'Cost increases','rule':'Receipt weight lowers the tray.','persistence':'Retain all previous mechanisms simply because they were built.'}],['STATE_ACCUMULATION_WITHOUT_MEANING'])
 token={'id':'sample','origin_setup':'s1','state_at_origin':'folded paper with a corner nick','setups_used':['s1','s2'],'state_changes':[{'setup_id':'s1','change':'Lens exposes the sample route gap.'},{'setup_id':'s2','change':'Its gap is aligned against a complete reference.'}],'final_destination':'Comparison slot, still identifiable by its nick.','story_justification':'The same inspected sample must be compared with the reference.'}
 fixture('g',[('Inspect this small sample.','sample','Bot opens a nicked sample beneath a lens.','Folded sample enters.','Its gap is exposed.','Large sample and lens, Bot at right; sample leaves frame before cut.'),('Compare it with the reference.','sample','Bot slides that SAME nicked sample next to a complete reference on a separate comparison rail.','Nicked sample arrives on the new slate comparison rail; lens and old set are absent.','The route gap is visibly aligned beside the intact reference.','Paired samples fill a detail crop; Bot below, different silhouette and camera scale.')],[{'beats':['b1'],'center':'Inspect a sample','rule':'Lens exposes a route gap.','persistence':'One gap is revealed.','reset':'Inspection becomes comparison; only the sample travels.'},{'beats':['b2'],'center':'Compare the same sample','rule':'Alignment against an intact reference reveals the missing route.','archetype':'comparison','palette':'slate / cream','persistence':'The identifiable sample supplies continuity while the visual rule changes.'}],['PASS'],token)
 fixture('h',[('Join these two pieces.','paper halves','Bot pushes two large paper halves together.','Halves are apart.','Halves join.','The joint is visible centrally; six extra decorative gears, pipes, unused receipt boxes and competing signs are placed around it solely to fill space, without story, location or balance function.')],[{'beats':['b1'],'center':'Join two pieces','rule':'A closed gap forms one connected object.','persistence':'Add decorative machinery simply to make the frame look busy.'}],['CLUTTER_WITHOUT_PURPOSE'])
 fixture('i',[('A closed route can carry it.','route and token','The route bridge slides into its gap and the token crosses.','The token is blocked at a visible gap.','The closed bridge visibly carries the token across.','A broad route fills a close crop with just a paper backdrop and route support; no Bot.','absent')],[{'beats':['b1'],'center':'A repaired route carries its token','rule':'A closed connection permits transit.','persistence':'The bridge closure and token crossing develop one rule. Bot has no causal or orientation role.'}],['PASS'])
 fixture('j',[('Only tested answers should win.','blank answer card','The unchanged blank card floats decoratively while captions state that one answer was tested and selected.','A blank card rests on a surface.','The same blank card rests on the surface; no test or comparison or selection is visible.','One blank card, a small Bot beside it, and a large caption containing the entire conclusion.')],[{'beats':['b1'],'center':'Select after testing','rule':'Captions explain that testing preceded selection; the card is unchanged.','persistence':'Keep the static card as an illustration while text supplies meaning.'}],['CAPTION_CARRIES_STORY'])
 print('10 planning fixtures authored and integrity checked')
if __name__=='__main__':main()
